services:
  postgresSQL:
    image: postgres:latest
    environment:
      POSTGRES_USER: localdbt
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdbt
    ports:
      - 54325:5432
    volumes:
      - "C:/Users/beaut/Documents/dagater_dbt/my-dagster-project/database:/var/lib/postgresql/data"
